import { ThemeProvider } from "@/components/provider/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { viVN } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Lusitana, Merriweather } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/system";
import { cn } from "@/lib/utils";
import "@blocknote/core/fonts/inter.css";
import "@blocknote/mantine/style.css";

const lusitana = Merriweather({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      localization={viVN}
      appearance={{
        elements: {
          footer: "hidden",
        },
      }}
    >
      <html lang="en">
        <body>
          <EdgeStoreProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NextUIProvider
                className={cn(
                  "size-full min-h-screen antialiased",
                  lusitana.className
                )}
              >
                {children}
              </NextUIProvider>
            </ThemeProvider>
          </EdgeStoreProvider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
